aws-ebs-csi-driver:
  version: 2.36.0
  source: https://kubernetes-sigs.github.io/aws-ebs-csi-driver/index.yaml
  external: true
cert-manager:
  version: 1.16.1
  source: https://charts.jetstack.io/index.yaml
  external: true
cluster-autoscaler:
  version: 9.43.0
  source: https://kubernetes.github.io/autoscaler/index.yaml
  external: true
external-dns:
  version: 8.3.9
  source: https://charts.bitnami.com/bitnami/index.yaml
  external: true
ingress-nginx:
  version: 4.11.3
  source: https://kubernetes.github.io/ingress-nginx/index.yaml
  external: true
kyverno:
  version: 2.7.3
  source: https://kyverno.github.io/kyverno/index.yaml
  external: true
  pin: true
metrics-server:
  version: 3.12.2
  source: https://kubernetes-sigs.github.io/metrics-server/index.yaml
  external: true
snapshot-controller:
  version: 3.0.6
  source: https://piraeus.io/helm-charts/index.yaml
  external: true
terranetes-controller:
  version: 0.7.21
  source: https://terranetes-controller.appvia.io/index.yaml
  external: true
tigera-operator:
  version: 3.28.2
  source: https://projectcalico.docs.tigera.io/charts/index.yaml
  external: true
